/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminScholarshipsRouteImport } from './routes/admin.scholarships'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPortalRouteImport } from './routes/admin.portal'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminLecturersRouteImport } from './routes/admin.lecturers'
import { Route as AdminGradesRouteImport } from './routes/admin.grades'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminEnrollmentRouteImport } from './routes/admin.enrollment'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScholarshipsRoute = AdminScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortalRoute = AdminPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLecturersRoute = AdminLecturersRouteImport.update({
  id: '/lecturers',
  path: '/lecturers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGradesRoute = AdminGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentRoute = AdminEnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/grades': typeof AdminGradesRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/portal': typeof AdminPortalRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scholarships': typeof AdminScholarshipsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/grades': typeof AdminGradesRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/portal': typeof AdminPortalRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scholarships': typeof AdminScholarshipsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/grades': typeof AdminGradesRoute
  '/admin/lecturers': typeof AdminLecturersRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/portal': typeof AdminPortalRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scholarships': typeof AdminScholarshipsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/attendance'
    | '/admin/classes'
    | '/admin/enrollment'
    | '/admin/finance'
    | '/admin/grades'
    | '/admin/lecturers'
    | '/admin/news'
    | '/admin/portal'
    | '/admin/reports'
    | '/admin/scholarships'
    | '/admin/students'
    | '/admin/timetable'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/attendance'
    | '/admin/classes'
    | '/admin/enrollment'
    | '/admin/finance'
    | '/admin/grades'
    | '/admin/lecturers'
    | '/admin/news'
    | '/admin/portal'
    | '/admin/reports'
    | '/admin/scholarships'
    | '/admin/students'
    | '/admin/timetable'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/attendance'
    | '/admin/classes'
    | '/admin/enrollment'
    | '/admin/finance'
    | '/admin/grades'
    | '/admin/lecturers'
    | '/admin/news'
    | '/admin/portal'
    | '/admin/reports'
    | '/admin/scholarships'
    | '/admin/students'
    | '/admin/timetable'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scholarships': {
      id: '/admin/scholarships'
      path: '/scholarships'
      fullPath: '/admin/scholarships'
      preLoaderRoute: typeof AdminScholarshipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portal': {
      id: '/admin/portal'
      path: '/portal'
      fullPath: '/admin/portal'
      preLoaderRoute: typeof AdminPortalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lecturers': {
      id: '/admin/lecturers'
      path: '/lecturers'
      fullPath: '/admin/lecturers'
      preLoaderRoute: typeof AdminLecturersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grades': {
      id: '/admin/grades'
      path: '/grades'
      fullPath: '/admin/grades'
      preLoaderRoute: typeof AdminGradesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollment': {
      id: '/admin/enrollment'
      path: '/enrollment'
      fullPath: '/admin/enrollment'
      preLoaderRoute: typeof AdminEnrollmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminEnrollmentRoute: typeof AdminEnrollmentRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminGradesRoute: typeof AdminGradesRoute
  AdminLecturersRoute: typeof AdminLecturersRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminPortalRoute: typeof AdminPortalRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminScholarshipsRoute: typeof AdminScholarshipsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminEnrollmentRoute: AdminEnrollmentRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminGradesRoute: AdminGradesRoute,
  AdminLecturersRoute: AdminLecturersRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminPortalRoute: AdminPortalRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminScholarshipsRoute: AdminScholarshipsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTimetableRoute: AdminTimetableRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
